# @package _global_

defaults:
  - _self_
  - datamodule: single_biomed.yaml # choose datamodule with `test_dataloader()` for evaluation
  - model: gpt3.yaml
  - logger: null
  - trainer: default.yaml
  - paths: default.yaml
  - extras: default.yaml
  - hydra: default.yaml

  # experiment configs allow for version control of specific hyperparameters
  # e.g. best hyperparameters for given model and datamodule
  - experiment: null

task_name: "eval"

tags: ["dev"]

seed: 42

# passing checkpoint path is necessary for evaluation
ckpt_path: ???
