nld:
  begin_entity_token: '['
  separator_token: 'of'
  relation_separator_token: 'and'
  end_entity_token: ']'
  query_separator_token: 'by'
  example_separator: '###'
  head: 'Convert:'
  example_head: 'Input: '
  output_head: 'Output: '

  replace: True
  skip_example_with_special_token: True
  reformat_begin_entity_token: '('
  reformat_end_entity_token: ')'