nld:
  begin_entity_token: '['
  separator_token: '|'
  relation_separator_token: '='
  end_entity_token: ']'
  query_separator_token: ':'
  example_separator: '###'
  head: 'Find Events:'
  example_head: 'Example: '
  output_head: 'Events: '

  replace: True
  skip_example_with_special_token: False
  reformat_begin_entity_token: '('
  reformat_end_entity_token: ')'